# ===================================================================
# AMBIENTE: DESENVOLVIMENTO (H2 Database + Offline Mock AI)
# ===================================================================

# Banco de Dados H2 em Memoria
spring.datasource.url=jdbc:h2:mem:voxpixdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Habilita o Console do H2 no navegador (/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Credenciais ficticias para execucao local e testes automatizados da DIO
api.groq.url=http://localhost:8080/mock/groq
api.groq.key=groq_mock_key_explicit_for_evaluation_sprint_3

api.gemini.url=http://localhost:8080/mock/gemini
api.gemini.key=gemini_mock_key_explicit_for_evaluation_sprint_3
