# ===================================================================
# CONFIGURACOES GLOBAIS - VOX PIX API
# ===================================================================
spring.application.name=vox-pix-api
server.port=8080

# Define o perfil de execucao ativo como "dev" por padrao
# Isso iniciara o banco H2 em memoria e os servicos simulados (offline) de IA
spring.profiles.active=dev
